apiVersion: skaffold/v4beta13
kind: Config
build: 
  artifacts:
    - image: thomastheprogrammer/auth-service
      context: auth
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: thomastheprogrammer/ticket-service
      context: tickets
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
      docker:
        dockerfile: Dockerfile
    - image: thomastheprogrammer/orders-service
      context: orders
      sync: 
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: thomastheprogrammer/client-service
      context: client
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.js"
          - "**/*.jsx"
          - "**/*.css"
      docker:
        dockerfile: Dockerfile  # Changed from Dockerfile.dev
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - infra/k8s/*
deploy:
  kubectl: {}
  statusCheckDeadlineSeconds: 600