import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import ReactQueryProvider from "@/components/providers/QueryClientProvider";
import { Theme } from "@/components/providers/ThemeProvider";
import ToastProvider from "@/components/providers/ToastProvider";
import BackToTopButton from "@/components/ui/BackToTop";

// Font optimization
const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
	variable: "--font-poppins",
	display: "swap", // Ensures text remains visible during font loading
});

// Viewport configuration for responsive design and mobile optimization
export const viewport: Viewport = {
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "#ffffff" },
		{ media: "(prefers-color-scheme: dark)", color: "#0f172a" },
	],
	width: "device-width",
	initialScale: 1,
	maximumScale: 5,
	userScalable: true,
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
                suppressHydrationWarning
				className="font-sans antialiased flex min-h-screen flex-col"
			>
                <ReactQueryProvider>
                    <Theme>
                        <ToastProvider />
                        {children}
                        <BackToTopButton />
                    </Theme>
                </ReactQueryProvider>
			</body>
		</html>
	);
}
